# Modified project configuration derived from OpenMMLab MMDetection recipes.
# Original OpenMMLab copyright/license retained; see THIRD_PARTY_NOTICES.md
# and licenses/MMDetection-Apache-2.0.txt.
# Path-only publication adaptation; historical preprocessing is unchanged.
# Generated by tools/export_training_configs.py; see manifest.json for hashes.
"""FP32 focal-loss repair of v2; the rest of its training recipe is unchanged.

New output identity preserves all prior checkpoints and evaluation provenance.
The repair is numerical only: same seed, COCO initialization, batch size, LR,
gradient clipping, schedule, data transforms and 12-epoch training duration.
"""
_base_ = './bdd10k_ft_reppoints_r50_v2.py'

custom_imports = dict(imports=['training.reppoints_numerics'], allow_failed_imports=False)
custom_hooks = [dict(type='FiniteTrainingLossHook')]
model = dict(bbox_head=dict(loss_cls=dict(type='Float32FocalLoss')))
work_dir = 'work_dirs/bdd10k_ft_reppoints_r50_v3'
train_cfg = dict(max_epochs=12, type='EpochBasedTrainLoop', val_interval=12)
resume = False
lego_provenance = dict(
    date='2026-09-20',
    numerical_repair='FP32 focal forward/backward within otherwise unchanged AMP',
    replaces='bdd10k_ft_reppoints_r50_v2')
