# Project recipe derived from OpenMMLab MMDetection.
# See THIRD_PARTY_NOTICES.md and licenses/MMDetection-Apache-2.0.txt.
# Portable path adaptation; model and training settings are unchanged.
# Generated by tools/build_model_zoo.py.
_common_ds_kw = dict(
    data_prefix=dict(img='images/'),
    data_root=
    'data/Dataset/SeaDronesSeeObjectDetectionv2/mmdet_format/',
    metainfo=dict(classes=[
        'swimmer',
        'boat',
        'jetski',
        'life_saving_appliances',
        'buoy',
    ]),
    type='CocoDataset')
_norm = dict(
    mean=[
        123.675,
        116.28,
        103.53,
    ],
    std=[
        58.395,
        57.12,
        57.375,
    ],
    to_rgb=True,
    type='Normalize')
_train_pipeline = [
    dict(to_float32=True, type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='PhotoMetricDistortion'),
    dict(
        crop_size=(
            512,
            512,
        ),
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        ratios=(
            0.6,
            1.4,
        ),
        std=[
            58.395,
            57.12,
            57.375,
        ],
        test_mode=False,
        test_pad_mode=None,
        to_rgb=True,
        type='RandomCenterCropPad'),
    dict(prob=0.5, type='RandomFlip'),
    dict(keep_ratio=False, scale=(
        512,
        512,
    ), type='Resize'),
    dict(
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        std=[
            58.395,
            57.12,
            57.375,
        ],
        to_rgb=True,
        type='Normalize'),
    dict(size=(
        512,
        512,
    ), type='Pad'),
    dict(type='PackDetInputs'),
]
_val_test_pipeline = [
    dict(to_float32=True, type='LoadImageFromFile'),
    dict(
        border=None,
        crop_size=None,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        ratios=None,
        std=[
            58.395,
            57.12,
            57.375,
        ],
        test_mode=True,
        test_pad_mode=[
            'size_divisor',
            32,
        ],
        to_rgb=True,
        type='RandomCenterCropPad'),
    dict(keep_ratio=False, scale=(
        512,
        512,
    ), type='Resize'),
    dict(
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        std=[
            58.395,
            57.12,
            57.375,
        ],
        to_rgb=True,
        type='Normalize'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
            'border',
        ),
        type='PackDetInputs'),
]
auto_scale_lr = dict(base_batch_size=128, enable=False)
backend_args = None
classes = [
    'swimmer',
    'boat',
    'jetski',
    'life_saving_appliances',
    'buoy',
]
data_root = 'data/Dataset/SeaDronesSeeObjectDetectionv2/mmdet_format/'
dataset_type = 'CocoDataset'
default_hooks = dict(
    checkpoint=dict(interval=1, type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(type='DetVisualizationHook'))
default_scope = 'mmdet'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
launcher = 'none'
load_cfg = dict(strict=False)
load_from = 'checkpoints/centernet_resnet18_140e_coco_20210705_093630-bb5b3bf7.pth'
log_level = 'INFO'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
max_epochs = 28
model = dict(
    backbone=dict(
        depth=18,
        init_cfg=dict(checkpoint='torchvision://resnet18', type='Pretrained'),
        norm_cfg=dict(type='BN'),
        norm_eval=False,
        type='ResNet'),
    bbox_head=dict(
        feat_channels=64,
        in_channels=64,
        loss_center_heatmap=dict(loss_weight=1.0, type='GaussianFocalLoss'),
        loss_offset=dict(loss_weight=1.0, type='L1Loss'),
        loss_wh=dict(loss_weight=0.1, type='L1Loss'),
        num_classes=5,
        type='CenterNetHead'),
    data_preprocessor=dict(
        bgr_to_rgb=True,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        std=[
            58.395,
            57.12,
            57.375,
        ],
        type='DetDataPreprocessor'),
    neck=dict(
        in_channels=512,
        num_deconv_filters=(
            256,
            128,
            64,
        ),
        num_deconv_kernels=(
            4,
            4,
            4,
        ),
        type='CTResNetNeck',
        use_dcn=True),
    test_cfg=dict(local_maximum_kernel=3, max_per_img=100, topk=100),
    train_cfg=None,
    type='CenterNet')
num_classes = 5
optim_wrapper = dict(
    clip_grad=dict(max_norm=1.0, norm_type=2),
    optimizer=dict(lr=0.02, momentum=0.9, type='SGD', weight_decay=0.0001))
param_scheduler = [
    dict(
        begin=0, by_epoch=False, end=1000, start_factor=0.001,
        type='LinearLR'),
    dict(by_epoch=True, gamma=0.1, milestones=[
        16,
        22,
    ], type='MultiStepLR'),
]
resume = False
test_cfg = dict(type='TestLoop')
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='annotations/instances_val.json',
        data_prefix=dict(img='images/'),
        data_root=
        'data/Dataset/SeaDronesSeeObjectDetectionv2/mmdet_format/',
        metainfo=dict(classes=[
            'swimmer',
            'boat',
            'jetski',
            'life_saving_appliances',
            'buoy',
        ]),
        pipeline=[
            dict(to_float32=True, type='LoadImageFromFile'),
            dict(
                border=None,
                crop_size=None,
                mean=[
                    123.675,
                    116.28,
                    103.53,
                ],
                ratios=None,
                std=[
                    58.395,
                    57.12,
                    57.375,
                ],
                test_mode=True,
                test_pad_mode=[
                    'size_divisor',
                    32,
                ],
                to_rgb=True,
                type='RandomCenterCropPad'),
            dict(keep_ratio=False, scale=(
                512,
                512,
            ), type='Resize'),
            dict(
                mean=[
                    123.675,
                    116.28,
                    103.53,
                ],
                std=[
                    58.395,
                    57.12,
                    57.375,
                ],
                to_rgb=True,
                type='Normalize'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                    'border',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    num_workers=2)
test_evaluator = dict(
    ann_file=
    'data/Dataset/SeaDronesSeeObjectDetectionv2/mmdet_format/annotations/instances_val.json',
    metric='bbox',
    type='CocoMetric')
test_pipeline = [
    dict(backend_args=None, to_float32=True, type='LoadImageFromFile'),
    dict(
        border=None,
        mean=[
            0,
            0,
            0,
        ],
        ratios=None,
        std=[
            1,
            1,
            1,
        ],
        test_mode=True,
        test_pad_add_pix=1,
        test_pad_mode=[
            'logical_or',
            31,
        ],
        to_rgb=True,
        type='RandomCenterCropPad'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'border',
        ),
        type='PackDetInputs'),
]
train_cfg = dict(max_epochs=24, type='EpochBasedTrainLoop', val_interval=2)
train_dataloader = dict(
    batch_size=16,
    dataset=dict(
        ann_file='annotations/instances_train.json',
        data_prefix=dict(img='images/'),
        data_root=
        'data/Dataset/SeaDronesSeeObjectDetectionv2/mmdet_format/',
        filter_cfg=dict(filter_empty_gt=True, min_size=32),
        metainfo=dict(classes=[
            'swimmer',
            'boat',
            'jetski',
            'life_saving_appliances',
            'buoy',
        ]),
        pipeline=[
            dict(to_float32=True, type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(type='PhotoMetricDistortion'),
            dict(
                crop_size=(
                    512,
                    512,
                ),
                mean=[
                    123.675,
                    116.28,
                    103.53,
                ],
                ratios=(
                    0.6,
                    1.4,
                ),
                std=[
                    58.395,
                    57.12,
                    57.375,
                ],
                test_mode=False,
                test_pad_mode=None,
                to_rgb=True,
                type='RandomCenterCropPad'),
            dict(prob=0.5, type='RandomFlip'),
            dict(keep_ratio=False, scale=(
                512,
                512,
            ), type='Resize'),
            dict(
                mean=[
                    123.675,
                    116.28,
                    103.53,
                ],
                std=[
                    58.395,
                    57.12,
                    57.375,
                ],
                to_rgb=True,
                type='Normalize'),
            dict(size=(
                512,
                512,
            ), type='Pad'),
            dict(type='PackDetInputs'),
        ],
        type='CocoDataset'),
    num_workers=4)
train_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        brightness_delta=32,
        contrast_range=(
            0.5,
            1.5,
        ),
        hue_delta=18,
        saturation_range=(
            0.5,
            1.5,
        ),
        type='PhotoMetricDistortion'),
    dict(
        crop_size=(
            512,
            512,
        ),
        mean=[
            0,
            0,
            0,
        ],
        ratios=(
            0.6,
            0.7,
            0.8,
            0.9,
            1.0,
            1.1,
            1.2,
            1.3,
        ),
        std=[
            1,
            1,
            1,
        ],
        test_pad_mode=None,
        to_rgb=True,
        type='RandomCenterCropPad'),
    dict(keep_ratio=True, scale=(
        512,
        512,
    ), type='Resize'),
    dict(prob=0.5, type='RandomFlip'),
    dict(type='PackDetInputs'),
]
tta_model = dict(
    tta_cfg=dict(max_per_img=100, nms=dict(iou_threshold=0.5, type='nms')),
    type='DetTTAModel')
tta_pipeline = [
    dict(backend_args=None, to_float32=True, type='LoadImageFromFile'),
    dict(
        transforms=[
            [
                dict(prob=1.0, type='RandomFlip'),
                dict(prob=0.0, type='RandomFlip'),
            ],
            [
                dict(
                    border=None,
                    mean=[
                        0,
                        0,
                        0,
                    ],
                    ratios=None,
                    std=[
                        1,
                        1,
                        1,
                    ],
                    test_mode=True,
                    test_pad_add_pix=1,
                    test_pad_mode=[
                        'logical_or',
                        31,
                    ],
                    to_rgb=True,
                    type='RandomCenterCropPad'),
            ],
            [
                dict(type='LoadAnnotations', with_bbox=True),
            ],
            [
                dict(
                    meta_keys=(
                        'img_id',
                        'img_path',
                        'ori_shape',
                        'img_shape',
                        'flip',
                        'flip_direction',
                        'border',
                    ),
                    type='PackDetInputs'),
            ],
        ],
        type='TestTimeAug'),
]
val_cfg = dict(type='ValLoop')
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='annotations/instances_val.json',
        data_prefix=dict(img='images/'),
        data_root=
        'data/Dataset/SeaDronesSeeObjectDetectionv2/mmdet_format/',
        metainfo=dict(classes=[
            'swimmer',
            'boat',
            'jetski',
            'life_saving_appliances',
            'buoy',
        ]),
        pipeline=[
            dict(to_float32=True, type='LoadImageFromFile'),
            dict(
                border=None,
                crop_size=None,
                mean=[
                    123.675,
                    116.28,
                    103.53,
                ],
                ratios=None,
                std=[
                    58.395,
                    57.12,
                    57.375,
                ],
                test_mode=True,
                test_pad_mode=[
                    'size_divisor',
                    32,
                ],
                to_rgb=True,
                type='RandomCenterCropPad'),
            dict(keep_ratio=False, scale=(
                512,
                512,
            ), type='Resize'),
            dict(
                mean=[
                    123.675,
                    116.28,
                    103.53,
                ],
                std=[
                    58.395,
                    57.12,
                    57.375,
                ],
                to_rgb=True,
                type='Normalize'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                    'border',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    num_workers=2)
val_evaluator = dict(
    ann_file=
    'data/Dataset/SeaDronesSeeObjectDetectionv2/mmdet_format/annotations/instances_val.json',
    metric='bbox',
    type='CocoMetric')
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='DetLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
work_dir = 'work_dirs/seadronessee10k_ft_centernet_r18_dcn'
