#!/usr/bin/env python3
"""Build the four-domain catalog from full-validation metadata (CPU only).

Source directories are read-only. Only aggregate metrics, portable recipes and
file identities are exported; predictions, images and checkpoint binaries stay
outside the repository. Checkpoint files are hashed sequentially.
"""
import argparse
import ast
from collections import Counter, defaultdict
import csv
from datetime import datetime, timezone
import hashlib
import io
import json
import math
from pathlib import Path
import re

DOMAINS = {
    'bdd': ('BDD100K-FT', 'val', 'bdd_ft_val', 'BDD20K_FT.md'),
    'mobility': ('Mobility / CMA', 'cma_val', 'cma_val', 'Mobility.md'),
    'seadronessee': ('SeaDronesSee', 'sds_val', 'sds_val', 'SeaDronesSee.md'),
    'waid': ('WAID', 'waid_valid', 'waid_valid', 'WAID_FT.md'),
}
NAMES = {
    'atss_r50': 'ATSS R50', 'cascade_rcnn_r50': 'Cascade R-CNN R50',
    'centernet_r18_dcn': 'CenterNet R18-DCN', 'conditional_detr_r50': 'Conditional DETR R50',
    'ddq_detr4scale_r50': 'DDQ-DETR R50', 'deformable_detr_r50': 'Deformable DETR R50',
    'deformable_detr_refine_r50': 'Deformable DETR Refine R50', 'detr_r50': 'DETR R50',
    'diffusiondet_r50': 'DiffusionDet R50', 'dino_swin_l': 'DINO Swin-L',
    'dynamic_rcnn_r50': 'Dynamic R-CNN R50', 'efficientdet_d3': 'EfficientDet-D3',
    'fcos_r50': 'FCOS R50', 'frcnn_r50_fpn': 'Faster R-CNN R50-FPN',
    'freeanchor_r50': 'FreeAnchor R50', 'grid_rcnn_r50': 'Grid R-CNN R50',
    'mask_rcnn_swin_t': 'Mask R-CNN Swin-T', 'nas_fcos_r50': 'NAS-FCOS R50',
    'paa_r50': 'PAA R50', 'reppoints_r50': 'RepPoints R50',
    'retinanet_effb3': 'RetinaNet EfficientNet-B3', 'retinanet_pvtt': 'RetinaNet PVT-T',
    'retinanet_r50': 'RetinaNet R50', 'rtmdet_tiny': 'RTMDet-Tiny',
    'sparse_rcnn_r50': 'Sparse R-CNN R50', 'ssd300': 'SSD300',
    'tood_r50': 'TOOD R50', 'tridentnet_r50': 'TridentNet R50',
    'varifocalnet_r50': 'VarifocalNet R50', 'vitdet_b': 'ViTDet-B',
    'yolof_r50': 'YOLOF R50', 'yolov3_320': 'YOLOv3 Darknet-53 (320)',
}
METRICS = ('bbox_mAP', 'mAP50', 'mAP75', 'mAP_s', 'mAP_m', 'mAP_l')
HEADER = ('# Project recipe derived from OpenMMLab MMDetection.\n'
          '# See THIRD_PARTY_NOTICES.md and licenses/MMDetection-Apache-2.0.txt.\n'
          '# Portable path adaptation; model and training settings are unchanged.\n'
          '# Generated by tools/build_model_zoo.py.\n')


def digest(data):
    return hashlib.sha256(data).hexdigest()


def hash_file(path):
    before = path.stat()
    h = hashlib.sha256()
    with path.open('rb') as handle:
        for block in iter(lambda: handle.read(4 * 1024 * 1024), b''):
            h.update(block)
    after = path.stat()
    if (before.st_size, before.st_mtime_ns) != (after.st_size, after.st_mtime_ns):
        raise ValueError('File changed during hashing: ' + path.name)
    return h.hexdigest()


def portable_config(source, model):
    """Adapt storage literals only; prove that the rest of the AST is unchanged."""
    tree = ast.parse(source)
    provenance, workdirs = set(), set()
    for statement in tree.body:
        if isinstance(statement, ast.Assign):
            names = {n.id for n in statement.targets if isinstance(n, ast.Name)}
            target = provenance if 'lego_provenance' in names else workdirs if 'work_dir' in names else None
            if target is not None:
                target.update(id(n) for n in ast.walk(statement.value))
    data = source.encode()
    starts = [0]
    for line in data.splitlines(keepends=True):
        starts.append(starts[-1] + len(line))
    replacements = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Constant) or not isinstance(node.value, str):
            continue
        value = node.value
        new = value
        if id(node) in workdirs:
            new = 'work_dirs/' + model
        elif value.startswith('/'):
            if id(node) in provenance:
                new = Path(value).name
            elif Path(value).suffix in ('.pth', '.pt', '.ckpt'):
                new = 'checkpoints/' + Path(value).name
            else:
                match = re.search(r'/(bdd100k_ft/|Dataset/)(.*)$', value)
                if not match or '..' in Path(value).parts:
                    raise ValueError('Unknown storage literal in ' + model)
                new = 'data/' + match.group(1) + match.group(2)
        if new != value:
            replacements.append((starts[node.lineno - 1] + node.col_offset,
                                 starts[node.end_lineno - 1] + node.end_col_offset,
                                 repr(new).encode()))
            node.value = new
    for start, end, replacement in sorted(replacements, reverse=True):
        data = data[:start] + replacement + data[end:]
    result = HEADER + data.decode()
    if ast.dump(ast.parse(result)) != ast.dump(tree):
        raise ValueError('Non-path configuration edit')
    if re.search(r'/' + r'(?:home|media|mnt|Users)/', result):
        raise ValueError('Private path remains in ' + model)
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            if node.value.startswith(('/', '~', 'file://')):
                raise ValueError('Nonportable literal in ' + model)
    return result


def preferred(rows):
    """Choose a recipe revision, never the row with highest validation AP."""
    return max(rows, key=lambda r: (
        r['model'].endswith('_v2'),
        'smallobj' not in r['model'],
        'frcnn_r50_fpn' in r['model'],
        r['model']))


def status_label(row):
    labels = {
        'evaluated': 'Evaluated', 'training': 'Training',
        'numerical_issue': 'NaN in training', 'no_detections': 'No detections',
        'checkpoint_mismatch': 'Checkpoint unavailable',
    }
    result = labels[row['status']]
    if row.get('class_order_ok') is False:
        result += '; class-name mapping'
    return result


def format_ap(value):
    return '—' if value is None else '{:.2f}'.format(value * 100)


def render_domain(catalog, domain):
    title, _, _, _ = DOMAINS[domain]
    info = next(d for d in catalog['datasets'] if d['domain'] == domain)
    rows = [r for r in catalog['models'] if r['domain'] == domain]
    selected = [r for r in rows if r['primary']]
    extra = [r for r in rows if not r['primary']]
    train, val = info['splits']['train'], info['splits']['val']
    lines = ['# ' + title + ' model zoo', '',
             '[All domains](README.md) · [CSV](model_zoo/results.csv) · '
             '[Protocol](docs/evaluation.md) · [Training](docs/training-status.md)', '',
             'Snapshot: ' + catalog['as_of_utc'] + '. AP values use a 0–100 scale.', '',
             '| Train images | Validation images | Classes | Architecture slots |',
             '| ---: | ---: | ---: | ---: |',
             '| {:,} | {:,} | {} | {} |'.format(train['images'], val['images'], len(info['classes']), len(selected)), '',
             'Classes: ' + ', '.join('`' + c + '`' for c in info['classes']) + '.', '']
    if domain == 'bdd':
        lines += ['This is the project’s 11-class, 4,000-image validation split of BDD100K-FT.', '']
    lines += ['## Models', '',
              'Each row links to its recipe. Evaluated checkpoint filenames and SHA-256 '
              'identities are in the [catalog](model_zoo/catalog.json). Weight downloads '
              'are not hosted in this repository.', '',
              '| Model | AP | AP50 | AP75 | Status |', '| --- | ---: | ---: | ---: | --- |']
    for row in sorted(selected, key=lambda r: r['architecture']):
        metric = row.get('metrics') or {}
        label = NAMES[row['architecture']]
        if row['model'].endswith('_v2'):
            label += ' v2'
        lines.append('| [{}]({}) | {} | {} | {} | {} |'.format(
            label, row['config'], *(format_ap(metric.get(k)) for k in METRICS[:3]), status_label(row)))
    if extra:
        lines += ['', '## Other recorded revisions', '',
                  'Earlier runs and alternate recipes remain available separately; they do not '
                  'add architecture slots.', '',
                  '| Run / config | AP | AP50 | AP75 | Status |', '| --- | ---: | ---: | ---: | --- |']
        for row in extra:
            metric = row.get('metrics') or {}
            lines.append('| [{}]({}) | {} | {} | {} | {} |'.format(
                row['model'], row['config'], *(format_ap(metric.get(k)) for k in METRICS[:3]), status_label(row)))
    lines += ['', 'Native model test scales; COCO bbox AP with maxDets=100. '
              'Predictions use a 300-box cap where supported. '
              'See [evaluation details](docs/evaluation.md) and '
              '[known issues](docs/known-issues.md).', '']
    return '\n'.join(lines)


def build(source, repo):
    status = json.loads((repo / 'training/status.json').read_text())
    manifest = {r['model_dir']: r for r in csv.DictReader((source / 'results/manifest.csv').open())}
    summary_data = (source / 'results/dets/summary.csv').read_bytes()
    summary = list(csv.DictReader(io.StringIO(summary_data.decode())))
    records, artifacts, keys = [], {}, set()
    for domain, (_, split, folder, _) in DOMAINS.items():
        count = next(d for d in status['domains'] if d['domain'] == domain)['splits']['val']['images']
        for row in summary:
            if (row['split'], row['limit'], row['res']) != (split, '0', 'native'):
                continue
            model = row['model']
            if (domain, model) in keys:
                raise ValueError('Duplicate full-validation record')
            keys.add((domain, model))
            meta_path = source / 'results/dets' / folder / (model + '.meta.json')
            meta_bytes = meta_path.read_bytes()
            meta = json.loads(meta_bytes)
            if meta['model'] != model or meta['split'] != split or meta['n_images'] != count:
                raise ValueError('Metadata identity or split mismatch: ' + model)
            if meta['protocol']['scale'] not in ('native', 'native-config'):
                raise ValueError('Not a native-scale evaluation')
            for key in ('bbox_mAP', 'mAP50'):
                a, b = float(row[key]), float(meta[key])
                if not ((math.isnan(a) and math.isnan(b)) or abs(a - b) <= .000051):
                    raise ValueError('Summary and metadata disagree: ' + model)
            original = Path(meta['config']).read_bytes()
            exported = portable_config(original.decode(), model).encode()
            config = 'model_zoo/configs/' + domain + '/' + model + '.py'
            artifacts[config] = exported
            checkpoint = Path(meta['ckpt'])
            actual = hash_file(checkpoint) if checkpoint.is_file() else None
            matched = actual == meta['ckpt_sha256']
            state = 'evaluated'
            if not meta['n_dets']:
                state = 'no_detections'
            elif model == 'bdd10k_ft_reppoints_r50_v2':
                state = 'numerical_issue'
            elif not matched:
                state = 'checkpoint_mismatch'
            architecture = manifest[model]['arch_canonical']
            if architecture == 'freeanchor_r50_smallobj_fp32':
                architecture = 'freeanchor_r50'
            if architecture not in NAMES:
                raise ValueError('Unknown architecture: ' + architecture)
            metrics = {k: float(meta[k]) if math.isfinite(float(meta[k])) else None for k in METRICS}
            versions = {k: v for k, v in meta['versions'].items() if k != 'host'}
            record = dict(model=model, domain=domain, architecture=architecture,
                          primary=False, status=state, config=config,
                          config_source_sha256=digest(original), config_sha256=digest(exported),
                          source_metadata_sha256=digest(meta_bytes), split=split,
                          n_images=meta['n_images'], n_dets=meta['n_dets'], metrics=metrics,
                          evaluated_at_local=meta['date'], protocol=meta['protocol'],
                          class_order_ok=meta['class_order_ok'], model_classes=meta.get('model_classes'),
                          skipped_labels=meta.get('skipped_labels'), versions=versions,
                          checkpoint=dict(filename=checkpoint.name, evaluated_sha256=meta['ckpt_sha256'],
                                          available_file_sha256=actual, identity_matches=matched,
                                          download_url=None))
            records.append(record)
            print('{} {} {}'.format(domain, model, 'hash OK' if matched else 'HASH MISMATCH'), flush=True)
    for job in status['models']:
        if (job['domain'], job['model']) in keys:
            continue
        if job['status'] != 'training':
            raise ValueError('Recipe lacks full validation; review its status: ' + job['model'])
        arch = 'vitdet_b' if 'vitdet' in job['model'] else 'reppoints_r50'
        records.append(dict(model=job['model'], domain=job['domain'], architecture=arch,
                            primary=False, status='training', config=job['config'],
                            metrics=None, checkpoint=None))
    groups = defaultdict(list)
    for row in records:
        if not row['model'].endswith('_v3'):
            groups[(row['domain'], row['architecture'])].append(row)
    for group in groups.values():
        preferred(group)['primary'] = True
    for domain in DOMAINS:
        if {a for d, a in groups if d == domain} != set(NAMES):
            raise ValueError('Incomplete architecture catalog for ' + domain)
    catalog = dict(schema_version=1, as_of_utc=datetime.now(timezone.utc).isoformat(timespec='seconds'),
                   scope='Full native validation records plus two ongoing recipes; 32 architecture slots per domain.',
                   metric_scale='0 to 1 in JSON/CSV; 0 to 100 in Markdown',
                   evaluation_timezone='America/Los_Angeles',
                   selection='Latest v2 revision; canonical frcnn name over faster_rcnn alias; no AP-based selection.',
                   summary_source_sha256=digest(summary_data), datasets=status['domains'],
                   models=sorted(records, key=lambda r: (r['domain'], r['architecture'], r['model'])))
    artifacts['model_zoo/catalog.json'] = (json.dumps(catalog, indent=2, allow_nan=False) + '\n').encode()
    columns = ['domain', 'architecture', 'model', 'primary', 'status', 'split', 'n_images'] + list(METRICS) + ['config', 'checkpoint_sha256']
    stream = io.StringIO()
    writer = csv.DictWriter(stream, fieldnames=columns, lineterminator='\n')
    writer.writeheader()
    for row in catalog['models']:
        flat = {k: row.get(k, '') for k in columns}
        flat.update(row['metrics'] or {})
        flat['checkpoint_sha256'] = (row['checkpoint'] or {}).get('evaluated_sha256', '')
        writer.writerow(flat)
    artifacts['model_zoo/results.csv'] = stream.getvalue().encode()
    for domain, (_, _, _, page) in DOMAINS.items():
        artifacts[page] = render_domain(catalog, domain).encode()
    for name, data in artifacts.items():
        path = repo / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    print('Published records:', len(records), Counter(r['status'] for r in records))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source-root', type=Path, required=True)
    args = parser.parse_args()
    build(args.source_root.resolve(), Path(__file__).resolve().parents[1])
