#!/usr/bin/env python3
"""Export the explicit LEGO-AI training allowlist without importing ML code.

Only path literals and the public repair module import are adapted. The source
tree is read-only. Data, checkpoints, logs and third-party code are not copied.
"""

import argparse
import ast
import hashlib
import json
from pathlib import Path, PurePosixPath
import re


FORMAL_JOBS = (
    ("mobility10k_ft_fcos_r50", "cma_val"),
    ("mobility10k_ft_atss_r50", "cma_val"),
    ("mobility10k_ft_dynamic_rcnn_r50", "cma_val"),
    ("mobility10k_ft_rtmdet_tiny", "cma_val"),
    ("mobility10k_ft_yolof_r50", "cma_val"),
    ("mobility10k_ft_ssd300", "cma_val"),
    ("mobility10k_ft_deformable_detr_r50", "cma_val"),
    ("mobility10k_ft_mask_rcnn_swin_t", "cma_val"),
    ("mobility10k_ft_diffusiondet_r50", "cma_val"),
    ("seadronessee10k_ft_ssd300", "sds_val"),
    ("seadronessee10k_ft_deformable_detr_refine_r50", "sds_val"),
    ("seadronessee10k_ft_vitdet_b", "sds_val"),
    ("waid10k_ft_deformable_detr_refine_r50", "waid_valid"),
    ("waid10k_ft_vitdet_b", "waid_valid"),
    ("bdd10k_ft_reppoints_r50_v2", "val"),
    ("bdd10k_ft_efficientdet_d3_v2", "val"),
    ("seadronessee10k_ft_reppoints_r50_v2", "sds_val"),
    ("seadronessee10k_ft_freeanchor_r50_v2", "sds_val"),
    ("waid10k_ft_reppoints_r50_v2", "waid_valid"),
    ("waid10k_ft_freeanchor_r50_v2", "waid_valid"),
)
REPAIR_JOB = ("bdd10k_ft_reppoints_r50_v3", "val")
ALL_JOBS = FORMAL_JOBS + (REPAIR_JOB,)
PRIVATE_PATH = re.compile(r"/(?:home|media|mnt|tmp|Users)/")
HEADER = """# Modified project configuration derived from OpenMMLab MMDetection recipes.
# Original OpenMMLab copyright/license retained; see THIRD_PARTY_NOTICES.md
# and licenses/MMDetection-Apache-2.0.txt.
# Path-only publication adaptation; historical preprocessing is unchanged.
# Generated by tools/export_training_configs.py; see manifest.json for hashes.
"""


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def assignment(tree, name):
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == name
            for target in node.targets
        ):
            return node.value
    return None


def strings(node):
    if node is None:
        return []
    return [
        item for item in ast.walk(node)
        if isinstance(item, ast.Constant) and isinstance(item.value, str)
    ]


def assert_public_source(source):
    """Reject unknown absolute paths, including private paths in comments."""
    if PRIVATE_PATH.search(source):
        raise ValueError("Private host path remains in exported configuration")
    for node in strings(ast.parse(source)):
        if node.value.startswith(("/", "~", "file://")):
            raise ValueError("Absolute or user-specific path remains in export")


def sanitize_source(source, model, source_data_root):
    """Change designated string values, preserving the remaining source text."""
    if model not in dict(ALL_JOBS):
        raise ValueError("Model is outside the explicit publication allowlist")
    data_prefix = str(source_data_root).rstrip("/") + "/"
    if not data_prefix.startswith("/") or data_prefix == "/":
        raise ValueError("source_data_root must be a specific absolute directory")
    tree = ast.parse(source)
    provenance = {id(node) for node in strings(assignment(tree, "lego_provenance"))}
    output_paths = {id(node) for node in strings(assignment(tree, "work_dir"))}
    source_bytes = source.encode("utf-8")
    line_starts = [0]
    for line in source_bytes.splitlines(keepends=True):
        line_starts.append(line_starts[-1] + len(line))
    replacements = []
    for node in strings(tree):
        original = node.value
        replacement = original
        if id(node) in output_paths:
            replacement = "work_dirs/" + model
        elif original.startswith("/"):
            if id(node) in provenance:
                replacement = PurePosixPath(original).name
            elif PurePosixPath(original).suffix.lower() in (".pth", ".pt", ".ckpt"):
                replacement = "checkpoints/" + PurePosixPath(original).name
            elif original.startswith(data_prefix):
                suffix = original[len(data_prefix):]
                if ".." in PurePosixPath(suffix).parts:
                    raise ValueError("Dataset path escapes source data root")
                replacement = "data/" + suffix
            else:
                raise ValueError("Unrecognized absolute path in " + model)
        elif original == "reppoints_numerics":
            if model != REPAIR_JOB[0]:
                raise ValueError("Unexpected repair import in a formal job")
            replacement = "training.reppoints_numerics"
        if replacement != original:
            start = line_starts[node.lineno - 1] + node.col_offset
            end = line_starts[node.end_lineno - 1] + node.end_col_offset
            replacements.append((start, end, repr(replacement).encode("utf-8")))
            node.value = replacement
    for start, end, replacement in sorted(replacements, reverse=True):
        source_bytes = source_bytes[:start] + replacement + source_bytes[end:]
    exported = HEADER + source_bytes.decode("utf-8")
    if ast.dump(tree) != ast.dump(ast.parse(exported)):
        raise ValueError("Export unexpectedly changed non-path configuration structure")
    assert_public_source(exported)
    return exported


def verify_queue(source):
    match = re.search(r'^JOBS=\$\{JOBS:-"([^"\n]+)"\}', source, re.MULTILINE)
    if not match:
        raise ValueError("Cannot locate explicit default JOBS in source queue")
    jobs = tuple(tuple(item.split(":")) for item in match.group(1).split())
    if jobs != FORMAL_JOBS:
        raise ValueError("Source queue differs from the reviewed 20-job allowlist")


def make_manifest_entry(model, split, original, exported):
    tree = ast.parse(exported.decode("utf-8"))
    imports = [node.value for node in strings(assignment(tree, "custom_imports"))]
    checkpoints = sorted({
        node.value for node in strings(tree)
        if node.value.startswith("checkpoints/")
    })
    return {
        "model": model,
        "domain": model.split("10k_", 1)[0],
        "role": "repair_candidate" if model == REPAIR_JOB[0] else "formal_queue",
        "validation_split": split,
        "source_filename": model + ".py",
        "source_sha256": sha256(original),
        "published_filename": model + ".py",
        "published_sha256": sha256(exported),
        "custom_imports": imports,
        "checkpoint_files": checkpoints,
    }


def export_configs(source_root, source_data_root, output_dir, check=False):
    source_root = Path(source_root).resolve()
    output_dir = Path(output_dir).resolve()
    source_configs = source_root / "ft" / "configs"
    if output_dir == source_configs or source_configs in output_dir.parents:
        raise ValueError("Output must not overwrite the source configuration tree")
    queue_bytes = (source_root / "src" / "run_finetune.sh").read_bytes()
    verify_queue(queue_bytes.decode("utf-8"))
    artifacts = {}
    records = []
    for model, split in ALL_JOBS:
        original = (source_configs / (model + ".py")).read_bytes()
        exported = sanitize_source(
            original.decode("utf-8"), model, source_data_root
        ).encode("utf-8")
        artifacts[model + ".py"] = exported
        records.append(make_manifest_entry(model, split, original, exported))
    manifest = {
        "schema_version": 1,
        "scope": "20 formal queue recipes and one distinct numerical repair candidate",
        "exporter": "tools/export_training_configs.py",
        "queue_source_filename": "run_finetune.sh",
        "queue_source_sha256": sha256(queue_bytes),
        "formal_job_count": len(FORMAL_JOBS),
        "repair_candidate_count": 1,
        "checkpoints_included": False,
        "data_included": False,
        "adaptations": [
            "Dataset storage prefix becomes relative data/; suffixes are unchanged.",
            "Local checkpoint references become checkpoints/<basename>.",
            "work_dir becomes work_dirs/<model>.",
            "Absolute provenance values retain only their basename.",
            "Repair module import becomes training.reppoints_numerics.",
            "All other configuration values, including historical transforms, are retained.",
        ],
        "configs": records,
    }
    artifacts["manifest.json"] = (json.dumps(manifest, indent=2) + "\n").encode("utf-8")
    if check:
        mismatches = [
            name for name, data in artifacts.items()
            if not (output_dir / name).is_file() or (output_dir / name).read_bytes() != data
        ]
        if mismatches:
            raise ValueError("Published export differs: " + ", ".join(mismatches))
    else:
        output_dir.mkdir(parents=True, exist_ok=True)
        for name, data in artifacts.items():
            (output_dir / name).write_bytes(data)
    return len(records)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, required=True,
                        help="Read-only experiment directory with src/ and ft/configs/")
    parser.add_argument("--source-data-root", type=Path, required=True,
                        help="Absolute common storage prefix of the source datasets")
    parser.add_argument("--output-dir", type=Path,
                        default=Path(__file__).resolve().parents[1] / "training" / "configs")
    parser.add_argument("--check", action="store_true",
                        help="Compare deterministic exports; do not write files")
    args = parser.parse_args()
    count = export_configs(args.source_root, args.source_data_root, args.output_dir, args.check)
    print("{} {} configurations".format("Verified" if args.check else "Exported", count))


if __name__ == "__main__":
    main()
